"""empty message

Revision ID: fb95ebf4fa04
Revises: 717efed00424
Create Date: 2019-12-07 19:08:38.695886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb95ebf4fa04'
down_revision = '717efed00424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('members', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
